<a href="https://colab.research.google.com/github/9more/data_scientist/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [9]:
loan = pd.read_csv('/content/drive/MyDrive/loan_data.csv')

In [ ]:
loan.set_index='customer_id'

In [10]:
np.subtract(loan['customer_id'].unique().shape, loan.shape[0])

array([-17688])

In [12]:
loan['customer_id'].duplicated().sum()

np.int64(17688)

In [13]:
loan.set_index('customer_id', inplace=True)

In [15]:
loan.head()

,customer's_nth_loan,loan_signdate,loan_contractapproveddate,loan_principal,loan_status,customer_country,customer_date_of_birth,customer_monthly_salary,customer_credit_rating,total_collected
customer_id,,,,,,,,,,
988641,1,01/01/2011 11:59,NaN,200,SUSPENDED,Japan,25/11/1972,1500.0,700.0,0.0
307505,1,01/01/2011 12:12,02/01/2011 10:55,200,PAID IN FULL,Panama,28/06/1961,1117.0,760.0,428.0
766805,1,01/01/2011 16:05,02/01/2011 10:55,200,PAID IN FULL,France,28/05/1983,1600.0,760.0,1622.0
990925,1,01/01/2011 16:13,NaN,200,PAID IN FULL,Canada,06/03/1986,2634.0,740.0,437.0
991365,1,01/01/2011 17:23,NaN,200,SUSPENDED,Brazil,10/05/1957,2232.0,620.0,553.0

In [17]:
loan.sort_values(by="customer's_nth_loan", inplace=True, ascending=False)

In [22]:
loan.head(10)

,customer's_nth_loan,loan_signdate,loan_contractapproveddate,loan_principal,loan_status,customer_country,customer_date_of_birth,customer_monthly_salary,customer_credit_rating,total_collected
customer_id,,,,,,,,,,
82011,26,19/12/2012 15:36,19/12/2012 16:17,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,518.0
82011,25,21/11/2012 11:44,21/11/2012 11:52,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0
82011,24,11/10/2012 07:38,11/10/2012 08:03,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,518.0
82011,23,20/09/2012 11:51,20/09/2012 12:00,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0
82011,22,30/08/2012 20:16,31/08/2012 09:20,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0
82011,21,02/08/2012 14:39,03/08/2012 10:04,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0
82011,20,05/07/2012 06:47,05/07/2012 08:32,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0
82011,19,07/06/2012 11:08,07/06/2012 13:01,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0
243203,19,19/11/2012 09:20,19/11/2012 11:07,250,PAID IN FULL,Ireland,23/05/1951,1640.0,800.0,530.0
82011,18,10/05/2012 11:03,10/05/2012 11:20,300,PAID IN FULL,Israel,22/12/1961,1400.0,760.0,409.0

In [23]:
lst=loan['loan_status'].unique()

In [26]:
lst =list(lst)

In [32]:
enumerated_lst = list(enumerate(lst))

In [33]:
enumerated_lst

[(0, 'PAID IN FULL'),
 (1, 'BANK ACCOUNT CLOSED'),
 (2, 'SUSPENDED'),
 (3, 'CANCELED'),
 (4, 'ACTIVE'),
 (5, 'BANKRUPTCY CONFIRMED'),
 (6, 'COLLECTIONS'),
 (7, 'FINAL PAYMENT PENDING')]

In [ ]:
lst

In [31]:
loan.drop(loan[['loan_status']]==lst[1], axis=1,  inplace=True)